spring.jpa.hibernate.ddl-auto=create-drop
management.endpoints.web.exposure.include=prometheus,health,metrics
management.metrics.export.prometheus.enabled=true
server.port=0

# Enable graceful shutdown
server.shutdown=graceful
# Optional: how long Spring will wait for active requests to finish
spring.lifecycle.timeout-per-shutdown-phase=30s
